_wandb:
    value:
        cli_version: 0.21.4
        e:
            gtjympnl9q59n3lotjjcar8x0wyp2wd3:
                codePath: ResNet_train/train_ResNet_18_architecture.py
                codePathLocal: ResNet_train/train_ResNet_18_architecture.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "979998785536"
                        used: "417543782400"
                email: eltopchi3@gmail.com
                executable: /home/odin/miniconda3/envs/lerobot/bin/python
                git:
                    commit: fa72f537ad0f7e6d6b8e0bddb9337865ebeef986
                    remote: https://github.com/aburiz/Conuhacks2026.git
                gpu: NVIDIA GeForce RTX 5070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 6144
                      memoryTotal: "12820938752"
                      name: NVIDIA GeForce RTX 5070
                      uuid: GPU-7501b1c9-9eb0-ee9a-fbf7-3b85c97ec088
                host: ODIN-IEEE
                memory:
                    total: "98714808320"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.39
                program: /home/odin/conUhack_2026/Conuhacks2026/ResNet_train/train_ResNet_18_architecture.py
                python: CPython 3.10.18
                root: /home/odin/conUhack_2026/Conuhacks2026
                startedAt: "2026-01-25T08:47:42.936685Z"
                writerId: gtjympnl9q59n3lotjjcar8x0wyp2wd3
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
architecture:
    value: ResNet18_Modified
batch_size:
    value: 32
chunk_size:
    value: 10
epochs:
    value: 20
lr:
    value: 0.0001
output_dir:
    value: output
